cls

import delimited "/Users/cyberdim/Dropbox/Shared-Folder_Baxter-Javier/Orbis/Data_Raw/Business_Demography_SizeClass.csv", encoding(ISO-8859-2) clear

label var v11910 "Population of active enterprises in t - number "
label var v11920 "Births of enterprises in t - number "
label var v11930 "Deaths of enterprises in t - number "
label var v11941 "Enterprises newly born in t-1 having survived to t - number "
label var v11942 "Enterprises newly born in t-2 having survived to t - number "
label var v11943 "Enterprises newly born in t-3 having survived to t - number "
label var v11944 "Enterprises newly born in t-4 having survived to t - number "
label var v11945 "Enterprises newly born in t-5 having survived to t - number "
label var v16910 "Persons employed in the population of active enterprises in t - number "
label var v16911 "Employees in the population of active enterprises in t - number "
label var v16920 "Persons employed in the population of births in t - number "
label var v16921 "Employees in the population of births in t - number "
label var v16930 "Persons employed in the population of deaths in t - number "
label var v16931 "Employees in the population of deaths in t - number "
label var v16941 "Persons employed in the population of enterprises newly born in t-1 having survived to t - number "
label var v16942 "Persons employed in the population of enterprises newly born in t-2 having survived to t - number "
label var v16943 "Persons employed in the population of enterprises newly born in t-3 having survived to t - number "
label var v16944 "Persons employed in the population of enterprises newly born in t-4 having survived to t - number "
label var v16945 "Persons employed in the population of enterprises newly born in t-5 having survived to t - number "
label var v16951 "Persons employed in the year of birth in the population of enterprises newly born in t-1 having survived to t - number "
label var v16952 "Persons employed in the year of birth in the population of enterprises newly born in t-2 having survived to t - number "
label var v16953 "Persons employed in the year of birth in the population of enterprises newly born in t-3 having survived to t - number "
label var v16954 "Persons employed in the year of birth in the population of enterprises newly born in t-4 having survived to t - number "
label var v16955 "Persons employed in the year of birth in the population of enterprises newly born in t-5 having survived to t - number "
label var v97010 "Net business population growth - percentage "
label var v97015 "Business churn: birth rate + death rate - percentage "
label var v97020 "Birth rate: number of enterprise births in the reference period (t) divided by the number of enterprises active in t - percentage "
label var v97021 "Proportion of enterprise births in the reference period (t) by size class - percentage "
label var v97022 "Density of birth rate: number of enterprise births in the reference period (t) divided by the population (in 10,000) in t - percentage "
label var v97023 "Density of birth rate (narrow version): number of enterprise births in the reference period (t) divided by the population aged 20-59 (in 10,000) in t - percentage "
label var v97030 " Death rate: number of enterprise deaths in the reference period (t) divided by the number of enterprises active in t - percentage "
label var v97031 "Proportion of enterprise deaths in the reference period (t) by size class - percentage "
label var v97041 "Survival rate 1: number of enterprises in the reference period (t) newly born in t-1 having survived to t divided by the number of enterprise births in t-1 - percentage "
label var v97042 "Survival rate 2: number of enterprises in the reference period (t) newly born in t-2 having survived to t divided by the number of enterprise births in t-2 - percentage "
label var v97043 "Survival rate 3: number of enterprises in the reference period (t) newly born in t-3 having survived to t divided by the number of enterprise births in t-3 - percentage "
label var v97044 "Survival rate 4: number of enterprises in the reference period (t) newly born in t-4 having survived to t divided by the number of enterprise births in t-4 - percentage "
label var v97045 "Survival rate 5: number of enterprises in the reference period (t) newly born in t-5 having survived to t divided by the number of enterprise births in t-5 - percentage "
label var v97051 "1 year old enterprises' share of the business population - percentage "
label var v97052 "2 year old enterprises' share of the business population - percentage "
label var v97053 "3 year old enterprises' share of the business population - percentage "
label var v97054 "4 year old enterprises' share of the business population - percentage "
label var v97055 "5 year old enterprises' share of the business population - percentage "
label var v97120 "Employment share of enterprise births: number of persons employed in the reference period (t) among enterprises newly born in t divided by the number of persons employed in t among the stock of enterprises active in t - percentage "
label var v97121 "Average size of newly born enterprises: number of persons employed in the reference period (t) among enterprises newly born in t divided by the number of enterprises newly born in t - number "
label var v97122 "New enterprise paid employment rate: number of employees in the reference period (t) among enterprises newly born in t divided by the number of persons employed in t among enterprises newly born in t - percentage "
label var v97130 "Employment share of enterprise deaths: number of persons employed in the reference period (t) among enterprise deaths divided by the number of persons employed in t among the stock of active enterprises in t - percentage "
label var v97131 "Average employment in enterprise deaths: number of persons employed in the reference period (t) among enterprise deaths in t divided by the number of enterprise deaths in t - number "
label var v97141 "One-year old enterprises employment growth rate: number of persons employed in the reference period (t) among enterprises newly born in t-1 having survived to t divided by the number of persons employed in t-1 by the same enterprises, expressed as a percentage growth rate - percentage "
label var v97142 "Two-year old enterprises employment growth rate: number of persons employed in the reference period (t) among enterprises newly born in t-2 having survived to t divided by the number of persons employed in t-2 by the same enterprises, expressed as a percentage growth rate - percentage "
label var v97143  "Three-year old enterprises employment growth rate: number of persons employed in the reference period (t) among enterprises newly born in t-3 having survived to t divided by the number of persons employed in t-3 by the same enterprises, expressed as a percentage growth rate - percentage "
label var v97241 "Enterprises newly born in the year (n) having survived to n+1 - number "
label var v97242 "Enterprises newly born in the year (n) having survived to n+2 - number "
label var v97243 "Enterprises newly born in the year (n) having survived to n+3 - number "
label var v97244 "Enterprises newly born in the year (n) having survived to n+4 - number "
label var v97245 "Enterprises newly born in the year (n) having survived to n+5 - number "
label var v97251 "Cohort survival rate 1: newly born enterprises in the year (n) having survived to (n+1) divided by the number of enterprise births in (n) - number "
label var v97252 "Cohort survival rate 2: newly born enterprises in the year (n) having survived to (n+2) divided by the number of enterprise births in (n) - number "
label var v97253 "Cohort survival rate 3: newly born enterprises in the year (n) having survived to (n+3) divided by the number of enterprise births in (n) - number "
label var v97254 "Cohort survival rate 4: newly born enterprises in the year (n) having survived to (n+4) divided by the number of enterprise births in (n) - number "
label var v97255 "Cohort survival rate 5: newly born enterprises in the year (n) having survived to (n+5) divided by the number of enterprise births in (n) - number "
label var v97341 "Persons employed in the survival year among enterprises newly born in (n) having survived to n+1 - number "
label var v97342 "Persons employed in the survival year among enterprises newly born in (n) having survived to n+2 - number "
label var v97343 "Persons employed in the survival year among enterprises newly born in (n) having survived to n+3 - number "
label var v97344 "Persons employed in the survival year among enterprises newly born in (n) having survived to n+4 - number "
label var v97345 "Persons employed in the survival year among enterprises newly born in (n) having survived to n+5 - number "
label var v97351 "Persons employed in the year of birth in the population of enterprises newly born in (n) having survived to n+1 - number "
label var v97352 "Persons employed in the year of birth in the population of enterprises newly born in (n) having survived to n+2 - number "
label var v97353 "Persons employed in the year of birth in the population of enterprises newly born in (n) having survived to n+3 - number "
label var v97354 "Persons employed in the year of birth in the population of enterprises newly born in (n) having survived to n+4 - number "
label var v97355 "Persons employed in the year of birth in the population of enterprises newly born in (n) having survived to n+5 - number "
label var v97361 "One-year old enterprises employment growth rate: persons employed in the year (n+1) among enterprises newly born in (n) having survived to n+1 divided by the number of persons employed in (n) by the same enterprises - number "
label var v97362 "Two-year old enterprises employment growth rate: persons employed in the year (n+2) among enterprises newly born in (n) having survived to n+2 divided by the number of persons employed in (n) by the same enterprises - number "
label var v97363 "Three-year old enterprises employment growth rate: persons employed in the year (n+3) among enterprises newly born in (n) having survived to n+3 divided by the number of persons employed in (n) by the same enterprises - number "
label var v97364 "Four-year old enterprises employment growth rate: persons employed in the year (n+4) among enterprises newly born in (n) having survived to n+4 divided by the number of persons employed in (n) by the same enterprises - number "
label var v97365 "Five-year old enterprises employment growth rate: persons employed in the year (n+5) among enterprises newly born in (n) having survived to n+5 divided by the number of persons employed in (n) by the same enterprises - number "

save "/Users/cyberdim/Dropbox/Shared-Folder_Baxter-Javier/Orbis/Data_Cleaned/EuroStat_Business_Demography_SizeClass.dta", replace
