cls
clear all
import delimited "/Users/cyberdim/Dropbox/Shared-Folder_Baxter-Javier/Orbis/Data_Raw/EuroStat_Firms_Managed_Age_entrepreneur.csv", encoding(ISO-8859-2) clear


foreach v of varlist _a - v149{
   local x : variable label `v'
   rename `v' V`x'
}

drop v1

label var	V101_A	 " Number of employees in the year of enterprise birth "
label var	V101_N	 " Number of units having survived from 2002 to 2005 "
label var	V201_A	 " Start-up type - new enterprise "
label var	V201_C	 " Start-up type - reactivation after more than 2 years "
label var	V201_T	 " Start-up type - Total "
label var	V202_A	 " Start-up motivation - desire for new challenges "
label var	V202_B	 " Start-up motivation - desire to be one's own boss "
label var	V202_C	 " Start-up motivation - desire to make a living from a hobby activity "
label var	V202_D	 " Start-up motivation - tradition for self-employment in the family "
label var	V202_E	 " Start-up motivation - combining work and private life "
label var	V202_F	 " Start-up motivation - children are big enough "
label var	V202_G	 " Start-up motivation - prospect of making more money "
label var	V202_H	 " Start-up motivation - realising an idea for an new product or service "
label var	V202_I	 " Start-up motivation - reaching an international market "
label var	V202_J	 " Start-up motivation - avoiding unemployment "
label var	V202_K	 " Start-up motivation - getting away from unsatisfactory work situation "
label var	V202_L	 " Start-up motivation - working as sub-contractor exclusively for former employer "
label var	V202_M	 " Start-up motivation - only possibility to carry out profession "
label var	V202_T	 " Start-up motivation - Total "
label var	V203_A	 " Start-up financing - own funds or savings "
label var	V203_B	 " Start-up financing - financial assistance from family or friends "
label var	V203_C	 " Start-up financing - bank loan without collateral "
label var	V203_D	 " Start-up financing - bank loan with collateral "
label var	V203_E	 " Start-up financing - capital contribution from other enterprises "
label var	V203_F	 " Start-up financing - venture capital "
label var	V203_G	 " Start-up financing - financial support from public authorities "
label var	V203_T	 " Start-up financing - Total "
label var	V204_A	 " Start-up difficulties - to get financing "
label var	V204_B	 " Start-up difficulties - to establish contacts with customers "
label var	V204_C	 " Start-up difficulties - to obtain payment for outstanding invoices "
label var	V204_D	 " Start-up difficulties - to price goods or services "
label var	V204_E	 " Start-up difficulties - to find suitable premises "
label var	V204_F	 " Start-up difficulties - to find suppliers "
label var	V204_G	 " Start-up difficulties - to get suitable personnel "
label var	V204_H	 " Start-up difficulties - to use information technology effectively "
label var	V204_I	 " Start-up difficulties - to deal with legal / governmental / administrative matters "
label var	V204_J	 " Start-up difficulties - to be alone as an entrepreneur "
label var	V204_K	 " Start-up difficulties - to get backing from spouse or family "
label var	V204_T	 " Start-up difficulties - Total "
label var	V205_A	 " Previous occupation - employee "
label var	V205_B	 " Previous occupation - running another enterprise "
label var	V205_C	 " Previous occupation - student "
label var	V205_D	 " Previous occupation - unemployed and available to labour market "
label var	V205_E	 " Previous occupation - no gainful activity and not available to labour market "
label var	V205_T	 " Previous occupation - Total "
label var	V206_A	 " Previous branch experience - yes "
label var	V206_B	 " Previous branch experience - no "
label var	V206_T	 " Previous branch experience - total "
label var	V207_A	 " Previous experience running an enterprise - no "
label var	V207_B	 " Previous experience running an enterprise - once "
label var	V207_C	 " Previous experience running an enterprise - more than once "
label var	V207_T	 " Previous experience running an enterprise - Total "
label var	V208_A	 " Training received to help start-up - yes, on own initiative "
label var	V208_B	 " Training received to help start-up - yes, upon request of public authorities "
label var	V208_C	 " Training received to help start-up - none "
label var	V208_T	 " Training received to help start-up - Total "
label var	V209_A	 " Sources of advice - family and friends "
label var	V209_B	 " Sources of advice - training course for entrepreneurs "
label var	V209_C	 " Sources of advice - professional acquaintances "
label var	V209_D	 " Sources of advice - professional consultants "
label var	V209_E	 " Sources of advice - unemployment administration "
label var	V209_F	 " Sources of advice - organisations specialising in business start-ups "
label var	V209_G	 " Sources of advice - financial institution "
label var	V209_H	 " Sources of advice - no access to any relevant advice "
label var	V209_I	 " Sources of advice - no advice needed "
label var	V209_T	 " Sources of advice - Total "
label var	V210_A	 " Other current gainful activity - yes "
label var	V210_B	 " Other current gainful activity - no "
label var	V210_T	 " Other current gainful activity - Total "
label var	V214_A	 " Educational background - ISCED 1 or 2 "
label var	V214_B	 " Educational background - ISCED 3 "
label var	V214_C	 " Educational background - ISCED 4 "
label var	V214_D	 " Educational background - ISCED 5 or 6 "
label var	V214_T	 " Educational background - Total "
label var	V301_A	 " Current management - alone "
label var	V301_B	 " Current management - with someone else "
label var	V301_C	 " Current management - paid managers only "
label var	V301_T	 " Current management - Total "
label var	V302_A	 " Persons employed - unpaid or self-employed "
label var	V302_B	 " Persons employed - paid employees "
label var	V303_A	 " Turnover in 2004 "
label var	V304_A	 " Turnover in 2005 "
label var	V305_A	 " Origin of turnover - 1 customer "
label var	V305_B	 " Origin of turnover - 2 to 4 customers "
label var	V305_C	 " Origin of turnover - 5 or more customers "
label var	V305_T	 " Origin of turnover - Total "
label var	V306_A	 " Sales markets - local/regional "
label var	V306_B	 " Sales markets - national "
label var	V306_C	 " Sales markets - within EU "
label var	V306_D	 " Sales markets - outside EU "
label var	V306_T	 " Sales markets - Total "
label var	V307_A	 " Judgement of profitability - very good "
label var	V307_B	 " Judgement of profitability - good "
label var	V307_C	 " Judgement of profitability - barely sufficient "
label var	V307_D	 " Judgement of profitability - poor "
label var	V307_T	 " Judgement of profitability - Total "
label var	V308_A	 " Cooperation with other enterprises - in a network "
label var	V308_B	 " Cooperation with other enterprises - as subcontractor "
label var	V308_C	 " Cooperation with other enterprises - as a franchisee or licensee "
label var	V308_D	 " Cooperation with other enterprises - in a joint venture "
label var	V308_E	 " Cooperation with other enterprises - none / not relevant "
label var	V308_T	 " Cooperation with other enterprises - Total "
label var	V309_A	 " Innovation in the enterprise - product innovation "
label var	V309_B	 " Innovation in the enterprise - process innovation "
label var	V309_C	 " Innovation in the enterprise - organisational innovation "
label var	V309_D	 " Innovation in the enterprise - marketing innovation "
label var	V309_T	 " Innovation in the enterprise - Total "
label var	V310_A	 " Impediments to selling products or services - competition too vigorous "
label var	V310_B	 " Impediments to selling products or services - too little demand "
label var	V310_C	 " Impediments to selling products or services - difficult pricing "
label var	V310_D	 " Impediments to selling products or services - lack of marketing skills "
label var	V310_T	 " Impediments to selling products or services - Total "
label var	V311_A	 " Impediments to developing the business activity - profitability "
label var	V311_B	 " Impediments to developing the business activity - availability of bank loans "
label var	V311_C	 " Impediments to developing the business activity - availability of risk capital "
label var	V311_D	 " Impediments to developing the business activity - availability of short term credit "
label var	V311_E	 " Impediments to developing the business activity - availability of qualified personnel "
label var	V311_F	 " Impediments to developing the business activity - staff costs "
label var	V311_G	 " Impediments to developing the business activity - regulatory and administrative burden "
label var	V311_H	 " Impediments to developing the business activity - adapting to new technical standards "
label var	V311_I	 " Impediments to developing the business activity - availability of managerial competences "
label var	V311_J	 " Impediments to developing the business activity - combining family and work "
label var	V311_K	 " Impediments to developing the business activity - finding partners "
label var	V311_L	 " Impediments to developing the business activity - non or late paying customers "
label var	V311_T	 " Impediments to developing the business activity - Total "
label var	V401_A	 " Strategic plans - continuing the enterprise "
label var	V401_B	 " Strategic plans - affiliation "
label var	V401_C	 " Strategic plans - close and start new enterprise in the same activity "
label var	V401_D	 " Strategic plans - close and start new enterprise in another activity "
label var	V401_E	 " Strategic plans - close without starting new enterprise "
label var	V401_T	 " Strategic plans - Total "
label var	V402_A	 " Expected development of business activity - increase of turnover "
label var	V402_B	 " Expected development of business activity - increase of number of employees "
label var	V402_C	 " Expected development of business activity - increase of variety of goods and services for sale "
label var	V402_D	 " Expected development of business activity - increase of profitability "
label var	V402_T	 " Expected development of business activity - Total "
label var	V403_A	 " Highest priority if earnings increase - hire more employees "
label var	V403_B	 " Highest priority if earnings increase - increase remuneration of employees"
label var	V403_C	 " Highest priority if earnings increase - invest in the activity of the enterprise "
label var	V403_D	 " Highest priority if earnings increase - pay off loans or credits "
label var	V403_E	 " Highest priority if earnings increase - increase own salary from the enterprise "
label var	V403_F	 " Highest priority if earnings increase - reduce own working time "
label var	V403_G	 " Highest priority if earnings increase - none / not relevant "
label var	V403_T	 " Highest priority if earnings increase - Total "


save "/Users/cyberdim/Dropbox/Shared-Folder_Baxter-Javier/Orbis/Data_Cleaned/EuroStat_Firms_Managed_Age_entrepreneur.dta", replace
